---
disabled_rules:
  - type_body_length
  - file_length
  - function_body_length
opt_in_rules:
  - empty_count

force_cast: error
nesting:
  type_level: 2
force_try:
  severity: error
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
excluded:
  - ./Pods
  - ./PhotosAPIMocks/Sources/Sourcery/Generated/*
