codecov:
  require_ci_to_pass: true

coverage:
  range: 0..100
  round: down
  status:
    project:
      default:
        threshold: 1%

comment:
  behavior: new

ignore:
  - "./.github"
  - "./Pods"
  - "./PhotosAPIMocks"
  - "./FlickrSearchTests"
  - "./PhotosAPITests"
  - "./Dangerswift.swift"
