name: Changes labeler

on: [pull_request]

jobs:
  triage:
    name: Changes labeler
    runs-on: ubuntu-latest

    steps:
      - name: Label PR based on changes
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
