name: Swiftlint

# Documentation with macOS virtual environment:
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [pull_request]

jobs:
  swiftlint:
    name: Swiftlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
